docker run -d -p 8890:8888 -e USE_HTTPS=yes --name datascience_nb jupyter/datascience-notebook start-notebook.sh --NotebookApp.password='sha1:4f1dbadb99b7:bfa57f6971d81ee7d83e1ee8d4eae0062c506316'



# hash is generated by:
#In [1]: from IPython.lib import passwd
#In [2]: passwd()
#Enter password: **********
#Verify password: **********
#Out[2]: 'sha1:67c9e60bb8b6:9ffede0825894254b2e042ea597d771089e11aed'


docker run -d -p 8890:8888 -e USE_HTTPS=yes --name datascience_nb jupyter/datascience-notebook 
DS_SERVER=`docker ps | grep datascience_nb | awk '{print $1}'`
docker exec -it $DS_SERVER /bin/bash
start-notebook.sh --NotebookApp.password='sha1:4f1dbadb99b7:bfa57f6971d81ee7d83e1ee8d4eae0062c506316'


docker rm -f $DS_SERVER


